### ISSUE TITLE
 `CookieManager.getAll` failed

### ISSUE THREAD

**Issue by KingAmo** [safaiyeh/react-native-cookie-store#4]
error log info:
```
ExceptionsManager.js:126 RNCookieManagerIOS.getAll was called with 1 arguments but
 expects 0 arguments. If you haven't changed this method yourself, this usually means
 that your versions of the native code and JavaScript code are out of sync. 
Updating both should make this error go away.
```

**Comment by KingAmo** [comment]
i invested in the source code and find this:
![image](https://user-images.githubusercontent.com/29938227/71467063-90a20300-27fc-11ea-85f9-8dbcabbe75a0.png)
any help?

**Comment by safaiyeh** [comment]
@KingAmo Thanks for the issue.

Can you provide a code snippet on how you used this?

Thanks!

**Comment by safaiyeh** [comment]
@KingAmo could you test the branch in the PR and let me know if the exception is no longer thrown

**Comment by KingAmo** [comment]
```
    useEffect(() => {
        CookieManager.getAll()
            .then((res) => {
                console.log('CookieManager.getAll =>', res);
            });
    }, []);
```

the error still there in  `v3.2.3` , here is how i use it in iOS

**Comment by KingAmo** [comment]
error info: 
```
ExceptionsManager.js:126 RNCookieManagerIOS.getAll was called with 1 arguments but
 expects 0 arguments. If you haven't changed this method yourself, this usually means 
that your versions of the native code and JavaScript code are out of sync. Updating 
both should make this error go away.

```

**Comment by safaiyeh** [comment]
Yeah it is not in v3.2.3, just on the branch `ios-getAll-exception`

**Comment by safaiyeh** [comment]
https://github.com/safaiyeh/react-native-cookie-store/pull/10 is working for me locally, I'll merge it in and let you test it via npm

**Comment by safaiyeh** [comment]
Alrighty v3.2.4 is published, should fix this issue @KingAmo

**Comment by KingAmo** [comment]
@safaiyeh  thanks a lot, it is fixed
